### ISSUE TITLE
Configurar ambiente de trabajo local

### ISSUE THREAD

**Issue by camigomezdev** [camigomez35/programa2-pruebasSoftware#4]
#### Configurar ambiente de trabajo local

Camila
- [x] Instalar Go
- [x] Descargar proyecto
- [x] Ejecutar el proyecto

Jorge
- [x] Instalar Go
- [x] Descargar proyecto
- [x] Ejecutar el proyecto

Nilton
- [x] Instalar Go
- [x] Descargar proyecto
- [x] Ejecutar el proyecto

> Tiempo estimado: 30 minutos

**Comment by ElJorgeDiazT** [comment]
> Tiempo real: 1 hora

**Comment by camigomezdev** [comment]
> Tiempo real: 1 hora

**Comment by niltonsteveen** [comment]
Tiempo real: 1 hora
