### ISSUE TITLE
Aprender como hacer test en Go

### ISSUE THREAD

**Issue by camigomezdev** [camigomez35/programa2-pruebasSoftware#7]
#### Aprender como hacer test en Go

Camila
- [x] Buscar que librerías son útiles para hacer testing en Go
- [x] Realizar una prueba de iniciación

Jorge
- [x] Buscar que librerías son útiles para hacer testing en Go
- [x] Realizar una prueba de iniciación

Nilton
- [x] Buscar que librerías son útiles para hacer testing en Go
- [x] Realizar una prueba de iniciación

> Tiempo estimado: 1 hora

**Comment by camigomezdev** [comment]
> Tiempo real Camila: 1 hora y 30 minutos

**Comment by niltonsteveen** [comment]
con el import "testing" , se hace facilmente las pruebas:

package codebreaker

import "testing"

func TestEmpty(t *testing.T ){
  setCode("")
  expected := ""
  actual := validateCode("")
  if actual != expected {
    t.Errorf("Test failed, expected: '%s', got:  '%s'", expected, actual)
  }
}

**Comment by ElJorgeDiazT** [comment]
> Tiempo real: 1 hora
