### ISSUE TITLE
Aprender Go

### ISSUE THREAD

**Issue by camigomezdev** [camigomez35/programa2-pruebasSoftware#8]
#### Aprender go

Camila
- [x] Aprender a correr un proyecto
- [x] Aprender a declarar una variable
- [x] Aprender sobre for
- [x] Aprender sobre if
- [x] Aprender a declarar estructuras
- [x] Extras

Jorge
- [x] Aprender a correr un proyecto
- [x] Aprender a declarar una variable
- [x] Aprender sobre for
- [x] Aprender sobre if
- [x] Aprender a declarar estructuras
- [x] Extras

Nilton
- [x] Aprender a correr un proyecto
- [x] Aprender a declarar una variable
- [x] Aprender sobre for
- [x] Aprender sobre if
- [x] Aprender a declarar estructuras
- [x] Extras

> Tiempo estimado: 2 horas

**Comment by ElJorgeDiazT** [comment]
> Tiempo real: 4 horas

**Comment by camigomezdev** [comment]
> Tiempo real: 4 horas

**Comment by niltonsteveen** [comment]
Tiempo real: 2 horitas
